//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalHouseUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimalHouseUI.Localization.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyret blev ikke oprettet.  .
        /// </summary>
        internal static string AnimalNotCreated {
            get {
                return ResourceManager.GetString("AnimalNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyret blev ikke slettet. .
        /// </summary>
        internal static string AnimalNotDeleted {
            get {
                return ResourceManager.GetString("AnimalNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyret blev ikke rettet. .
        /// </summary>
        internal static string AnimalNotEdited {
            get {
                return ResourceManager.GetString("AnimalNotEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden kunne ikke oprettes, Muligvis er telefon -eller cvr-nummer ikke unikt. .
        /// </summary>
        internal static string CantCreateCustomer {
            get {
                return ResourceManager.GetString("CantCreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der kunne ikke udstedes recept. Medicin er muligvis ugyldig. .
        /// </summary>
        internal static string CantCreatePrescription {
            get {
                return ResourceManager.GetString("CantCreatePrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne Ikke Oprette et salg..
        /// </summary>
        internal static string CantCreateSale {
            get {
                return ResourceManager.GetString("CantCreateSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandlingen blev ikke gemt! prøv igen..
        ///   Looks up a localized string similar to Behandlingen blev ikke gemt! prøv igen. .
        /// </summary>
        internal static string CantCreateTreatment {
            get {
                return ResourceManager.GetString("CantCreateTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden kunne ikke slettes. .
        /// </summary>
        internal static string CantDeleteException {
            get {
                return ResourceManager.GetString("CantDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandlingen kunne ikke slettes. .
        /// </summary>
        internal static string CantDeleteTreatment {
            get {
                return ResourceManager.GetString("CantDeleteTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen over bure kunne ikke findes. .
        /// </summary>
        internal static string CantFindCages {
            get {
                return ResourceManager.GetString("CantFindCages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen over operationsstuer kunne ikke findes. .
        /// </summary>
        internal static string CantFindOperationRooms {
            get {
                return ResourceManager.GetString("CantFindOperationRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandlingen kunne ikke opdateres. .
        ///   Looks up a localized string similar to Recepten kunne ikke findes.
        /// </summary>
        internal static string CantGetUnPaidPrescription {
            get {
                return ResourceManager.GetString("CantGetUnPaidPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundes liste over dyr kunne ikke indlæses.
        /// </summary>
        internal static string CantGetAnimalList {
            get {
                return ResourceManager.GetString("CantGetAnimalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandlingen kunne ikke opdateres.
        /// </summary>
        internal static string CantUpdateTreatment {
            get {
                return ResourceManager.GetString("CantUpdateTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det var ikke muligt at redigere kunden. Muligvis er telefon -eller cvr-nummer optaget..
        /// </summary>
        internal static string CustomerNotUpdated {
            get {
                return ResourceManager.GetString("CustomerNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der var et problem med databasen.  .
        /// </summary>
        internal static string DefaultDatabaseError {
            get {
                return ResourceManager.GetString("DefaultDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalerne kunne ikke indlæses. .
        /// </summary>
        internal static string MedicalRecordEntryNotFound {
            get {
                return ResourceManager.GetString("MedicalRecordEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der var et problem med netværksforbindelsen. Tjek din internetforbindelse, og prøv igen. .
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev ikke fundet nogle kunder. .
        /// </summary>
        internal static string NoCustomerFound {
            get {
                return ResourceManager.GetString("NoCustomerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev ikke fundet nogle medarbejdere. .
        /// </summary>
        internal static string NoEmployeesFound {
            get {
                return ResourceManager.GetString("NoEmployeesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen varer blev fundet. .
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev ikke fundet nogle kunder, som der skal sendes påmindelser til. .
        /// </summary>
        internal static string NoRemindersFound {
            get {
                return ResourceManager.GetString("NoRemindersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev ikke fundet nogle behandlinger. .
        /// </summary>
        internal static string NoTreatmentsFound {
            get {
                return ResourceManager.GetString("NoTreatmentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandlingstyperne kunne ikke findes. .
        /// </summary>
        internal static string NoTreatmentTypesFound {
            get {
                return ResourceManager.GetString("NoTreatmentTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepterne kunne ikke indlæses. .
        /// </summary>
        internal static string PrescriptionNotFound {
            get {
                return ResourceManager.GetString("PrescriptionNotFound", resourceCulture);
            }
        }
    }
}
